### PR TITLE
onStart shouldnt be called by the ObservableToProducer

### PR DESCRIPTION
**Pull request by rozza**

### CODE REVIEW

**Comment by jyemin** [comment]
Can you explain the rationale for this change?  Is there a Jira issue that describes it?

**Comment by rozza** [comment]
Its being called internally by RxJava so we dont have to call it.

I noticed the side effect because when fixing the adapter test to be more predictable I used the TestScheduler and found that it was failing due to onStart being called multiple times.

Normally, onStart is an noop but it is needed for implementing back pressure.

**Comment by jyemin** [comment]
lgtm then

**Comment by rozza** [comment]
Updated.

**Pull request merged**
